pipeline {
    agent {
        docker {
            image 'node:19-alpine'
            args '-p 3000:3000'
        }
    }

    stages {
        stage('setup') {
            steps {
                
                sh 'cd frontend'
                sh 'npm install'
            }
        }
        stage('build') {
            steps {
                sh 'npm start build'
            }
        }
        stage('deploy') {
            steps {
                sshPublisher(
                    continueOnError: false,
                    failOnError: true,
                    alwaysPublishFromMaster: true,
                    publishers: [
                        sshPublisherDesc(
                            configName: "${env.SSH_CONFIG_NAME}",
                            verbose: true,
                            transfers: [
                                sshTransfer(
                                    sourceFiles: "build/*",
                                    removePrefix: "build/",
                                    cleanRemote: true
                                )
                            ]
                        )
                    ]

                )    
            }
        }
    }
}
