pipeline {
    agent {
        docker {
            image 'node:19-alpine'
            args '-p 3000:3000'
            args '-u root'
        }
    }
    
    stages {
        stage('build') {
            steps {
                dir('frontend') {
                    sh 'corepack enable'
                    sh 'yarn install'
                    sh 'yarn build'
                }
            }
        }
        stage('deploy') {
            steps {
                dir('frontend') {
                    sshPublisher(
                        continueOnError: false,
                        failOnError: true,
                        alwaysPublishFromMaster: true,
                        publishers: [
                            sshPublisherDesc(
                                configName: "${env.SSH_CONFIG_NAME}",
                                verbose: true,
                                transfers: [
                                    sshTransfer(
                                        sourceFiles: "build/*",
                                        removePrefix: "build/",
                                        cleanRemote: true
                                    )
                                ]
                            )
                        ]
                    )    
                }
            }
        }
    }
}
