version: '3'
services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - backend-data:/var/lib/postgresql/data/

volumes:
  backend-data:
    driver: local

