[general]
name=""
analytics=true

[general.currently_reading]
book=""
start_date=""

[general.colours]
textColour="#FFFFFF"
backgroundColour="#222629"
highlight="#86C232"
highlightDark="#61892F"
lightTone="#6B6E70"
darkTone="#474B4F"

# -------------------------------------------------------------------------- #

[pages]

[pages.home]
main_paragraph="""

"""

[pages.connect]
main_paragraph="""

"""
email=""

# Supported Links:
# Github
# Twitter
# LinkedIn

# Links in form
# [[pages.connect.links.link]]
# name="all lowercase"
# url=""

[[pages.connect.links]]
name=""
url=""


[pages.about]
main_paragraph="""

"""

[[pages.about.to_read]]

name=""
author=""

[[pages.about.finished]]

name=""
author=""
